/**
 * M0 contracts public API: strict Zod v4 schemas + inferred types for ids,
 * Run status, TurnInput, frozen context, RunResult, RunEvents, tools, and
 * the M0 HTTP DTOs. All boundary objects are strict (unknown keys rejected).
 *
 * M1 adds reference/Markdown contracts (see `./references.js`): canonical
 * resource / snapshot / session-reference / reference-set summaries and
 * details, reference-context CAS DTOs, stored-only API responses, Markdown
 * tool inputs/outputs with exact §14.6 bounds, freshness, reference error
 * codes, and the non-final `reference.presented` event. M0 registries stay
 * exact; `parseRunEvent` / `parseRunEventPayload` serve the latest (M2)
 * registry while `parseM0RunEvent` / `M0RunEventSchema` pin M0 assertions
 * and `parseM1RunEvent` / `M1RunEventSchema` pin M1 assertions.
 *
 * M2 adds StructuredAnswer contracts (see `./structured_answer.js`): exact
 * §15.8 part/text/citation/16KiB bounds with structural rN citations and
 * the reserved `answer.submit` terminal protocol name, plus model-step
 * contracts (see `./model.js`): the fixed redacted model/answer error
 * vocabulary and the non-final `model.step.started` / `model.step.completed`
 * / `model.step.failed` structural-metadata events. M0/M1 registries stay
 * exact; `M2*` / `Latest*` serve the latest (M2) registry.
 */

export type {
  LatestRunEvent,
  LatestRunEventType,
  M0RunEvent,
  M0RunEventType,
  M1RunEvent,
  M1RunEventType,
  M2RunEvent,
  M2RunEventType,
  RunEvent,
  TerminalEventType,
} from "./events.js";
export {
  isTerminalEventType,
  LATEST_RUN_EVENT_PAYLOAD_SCHEMAS,
  LATEST_RUN_EVENT_TYPES,
  LatestEventsResponseSchema,
  LatestRunEventSchema,
  LatestRunEventTypeSchema,
  LatestToolCompletedPayloadSchema,
  M0_RUN_EVENT_TYPES,
  M0RunCompletedPayloadSchema,
  M0RunEventSchema,
  M0RunEventTypeSchema,
  M0ToolCompletedPayloadSchema,
  M1_RUN_EVENT_PAYLOAD_SCHEMAS,
  M1_RUN_EVENT_TYPES,
  M1EventsResponseSchema,
  M1RunCompletedPayloadSchema,
  M1RunEventSchema,
  M1RunEventTypeSchema,
  M1ToolCompletedPayloadSchema,
  M2_RUN_EVENT_PAYLOAD_SCHEMAS,
  M2_RUN_EVENT_TYPES,
  M2EventsResponseSchema,
  M2RunEventSchema,
  M2RunEventTypeSchema,
  parseM0RunEvent,
  parseM0RunEventPayload,
  parseM1RunEvent,
  parseM1RunEventPayload,
  parseM2RunEvent,
  parseM2RunEventPayload,
  parseRunEvent,
  parseRunEventPayload,
  REFERENCE_PRESENTED_EVENT_TYPE,
  RUN_EVENT_PAYLOAD_SCHEMAS,
  RUN_EVENT_SCHEMA_VERSION,
  RunAbandonedPayloadSchema,
  RunCancelledPayloadSchema,
  RunCancelRequestedPayloadSchema,
  RunCompletedPayloadSchema,
  RunEventSchema,
  RunFailedPayloadSchema,
  RunQueuedPayloadSchema,
  RunStartedPayloadSchema,
  TERMINAL_EVENT_TYPES,
  TerminalEventTypeSchema,
  ToolCompletedPayloadSchema,
  ToolRequestedPayloadSchema,
} from "./events.js";
export type {
  FrozenContext,
  ReferenceContextSnapshot,
  TemporalContext,
} from "./frozen_context.js";
export {
  FrozenContextSchema,
  ReferenceContextSnapshotSchema,
  TemporalContextSchema,
} from "./frozen_context.js";
export type {
  AcceptedRun,
  ApiError,
  ApiErrorCode,
  CancelRunRequest,
  CancelRunResponse,
  CreateSessionRequest,
  CreateSessionResponse,
  EventsQuery,
  EventsQueryInput,
  EventsResponse,
  HealthLiveResponse,
  HealthReadyResponse,
  HistoryItem,
  HistoryQuery,
  HistoryQueryInput,
  HistoryResponse,
  IdempotencyLookupQuery,
  IdempotencyLookupResponse,
  M0EventsResponse,
  PostMessageRequest,
  PostMessageResponse,
  PostRetryRequest,
  PostRetryResponse,
  RunParams,
  SessionParams,
  TurnParams,
} from "./http.js";
export {
  AcceptedRunSchema,
  ApiErrorCodeSchema,
  ApiErrorSchema,
  CancelRunRequestSchema,
  CancelRunResponseSchema,
  CreateSessionRequestSchema,
  CreateSessionResponseSchema,
  EventsQuerySchema,
  EventsResponseSchema,
  HealthLiveResponseSchema,
  HealthReadyResponseSchema,
  HistoryItemSchema,
  HistoryQuerySchema,
  HistoryResponseSchema,
  IdempotencyLookupQuerySchema,
  IdempotencyLookupResponseSchema,
  M0EventsResponseSchema,
  PostMessageRequestSchema,
  PostMessageResponseSchema,
  PostRetryRequestSchema,
  PostRetryResponseSchema,
  RunParamsSchema,
  SessionParamsSchema,
  TurnParamsSchema,
} from "./http.js";
export type {
  IdempotencyKey,
  IdempotencyScope,
  Sha256Hex,
  UnixMs,
  Uuid,
} from "./ids.js";
export {
  IDEMPOTENCY_SCOPE_SESSIONS_CREATE,
  IdempotencyKeySchema,
  IdempotencyScopeSchema,
  messageScope,
  retryScope,
  Sha256HexSchema,
  UnixMsSchema,
  UUID_V4_REGEX,
  UuidSchema,
} from "./ids.js";
export type {
  M2ModelErrorCode,
  M2ModelErrorSchemaVersion,
  M2ModelStepEventType,
  ModelStepCompletedPayload,
  ModelStepDurationMs,
  ModelStepFailedPayload,
  ModelStepNumber,
  ModelStepStartedPayload,
  ModelStepUsage,
} from "./model.js";
export {
  KNOWN_M2_MODEL_ERROR_CODES,
  M2_MODEL_ERROR_CODE_REGISTRY,
  M2_MODEL_ERROR_CODES,
  M2_MODEL_STEP_EVENT_TYPES,
  M2ModelErrorCodeSchema,
  M2ModelStepEventTypeSchema,
  MAX_MODEL_STEPS_PER_RUN,
  ModelStepCompletedPayloadSchema,
  ModelStepDurationMsSchema,
  ModelStepFailedPayloadSchema,
  ModelStepNumberSchema,
  ModelStepStartedPayloadSchema,
  ModelStepUsageSchema,
  parseM2ModelErrorCode,
} from "./model.js";
export type {
  CanonicalKey,
  CanonicalResourceDetail,
  CanonicalResourceSummary,
  ExpandedLinkGraphBudget,
  ExpandedLinkGraphEntry,
  ExpandedLinkGraphKind,
  ExpandedLinkGraphStatus,
  Freshness,
  M1ReferenceErrorCode,
  M1ToolName,
  MarkdownSearchHit,
  MarkdownSearchSkippedEntry,
  MarkdownSearchSkippedReason,
  MarkdownSearchToolInput,
  MarkdownSearchToolInputInput,
  MarkdownSearchToolOutput,
  ReferenceApiError,
  ReferenceContextGetResponse,
  ReferenceContextItems,
  ReferenceContextPutRequest,
  ReferenceContextPutResponse,
  ReferenceContextVersion,
  ReferenceDetailResponse,
  ReferenceErrorCode,
  ReferenceListResponse,
  ReferenceOpenToolInput,
  ReferenceOpenToolOutput,
  ReferenceParams,
  ReferencePresentedPayload,
  ReferenceRefreshToolInput,
  ReferenceRefreshToolOutput,
  ReferenceRelatedEntry,
  ReferenceRelatedToolInput,
  ReferenceRelatedToolInputInput,
  ReferenceRelatedToolOutput,
  ReferenceSetDetail,
  ReferenceSetDetailResponse,
  ReferenceSetItem,
  ReferenceSetParams,
  ReferenceSetSummary,
  ReferenceTitle,
  ResourceSnapshotDetail,
  ResourceSnapshotSummary,
  SearchLimit,
  SearchQuery,
  SessionReferenceDetail,
  SessionReferenceSummary,
  SnapshotBody,
  Snippet,
  SourceRevision,
  StoredReferenceView,
} from "./references.js";
export {
  CanonicalKeySchema,
  CanonicalResourceDetailSchema,
  CanonicalResourceSummarySchema,
  countCodePoints,
  createExpandedLinkGraphBudget,
  DEFAULT_SEARCH_LIMIT,
  FreshnessSchema,
  M1_REFERENCE_ERROR_CODES,
  M1_TOOL_NAMES,
  M1ToolNameSchema,
  MAX_EXPANDED_LINK_GRAPH_BYTES,
  MAX_SEARCH_LIMIT,
  MAX_SEARCH_QUERY_CODE_POINTS,
  MAX_SNAPSHOT_BODY_BYTES,
  MAX_SNIPPET_CODE_POINTS,
  MAX_VAULT_FILES,
  MarkdownSearchHitSchema,
  MarkdownSearchSkippedEntrySchema,
  MarkdownSearchSkippedReasonSchema,
  MarkdownSearchToolInputSchema,
  MarkdownSearchToolOutputSchema,
  MIN_SEARCH_QUERY_CODE_POINTS,
  measureExpandedLinkGraphBytes,
  measureExpandedLinkGraphEntryBytes,
  ReferenceApiErrorSchema,
  ReferenceContextGetResponseSchema,
  ReferenceContextItemsSchema,
  ReferenceContextPutRequestSchema,
  ReferenceContextPutResponseSchema,
  ReferenceContextVersionSchema,
  ReferenceDetailResponseSchema,
  ReferenceErrorCodeSchema,
  ReferenceListResponseSchema,
  ReferenceOpenToolInputSchema,
  ReferenceOpenToolOutputSchema,
  ReferenceParamsSchema,
  ReferencePresentedPayloadSchema,
  ReferenceRefreshToolInputSchema,
  ReferenceRefreshToolOutputSchema,
  ReferenceRelatedEntrySchema,
  ReferenceRelatedToolInputSchema,
  ReferenceRelatedToolOutputSchema,
  ReferenceSetDetailResponseSchema,
  ReferenceSetDetailSchema,
  ReferenceSetItemSchema,
  ReferenceSetParamsSchema,
  ReferenceSetSummarySchema,
  ReferenceTitleSchema,
  ResourceSnapshotDetailSchema,
  ResourceSnapshotSummarySchema,
  SearchLimitSchema,
  SearchQuerySchema,
  SessionReferenceDetailSchema,
  SessionReferenceSummarySchema,
  SNAPSHOT_BODY_VERSION,
  SnapshotBodySchema,
  SnippetSchema,
  SourceRevisionSchema,
  StoredReferenceViewSchema,
  serializeExpandedLinkGraphEntry,
  utf8ByteLength,
} from "./references.js";
export type { RunResult, RunResultV1, RunResultV2 } from "./run_result.js";
export {
  buildRunResultV2,
  MAX_ASSISTANT_TEXT_LENGTH,
  parseM0RunResult,
  parseRunResult,
  RUN_RESULT_REGISTRY,
  RUN_RESULT_V2_VERSION,
  RunResultSchema,
  RunResultV1Schema,
  RunResultV2Schema,
  renderRunResultText,
} from "./run_result.js";
export type { ActiveStatus, RunStatus, TerminalStatus } from "./run_status.js";
export {
  ACTIVE_STATUSES,
  ActiveStatusSchema,
  isActiveStatus,
  isTerminalStatus,
  RunStatusSchema,
  TERMINAL_STATUSES,
  TerminalStatusSchema,
} from "./run_status.js";
export type {
  AnswerSubmitToolInput,
  CitationId,
  StructuredAnswer,
  StructuredAnswerPart,
  StructuredAnswerSchemaVersion,
} from "./structured_answer.js";
export {
  ANSWER_SUBMIT_TOOL_NAME,
  AnswerSubmitToolInputSchema,
  CITATION_ID_REGEX,
  CitationIdSchema,
  MAX_CITATIONS_PER_PART,
  MAX_PART_TEXT_CODE_POINTS,
  MAX_STRUCTURED_ANSWER_BYTES,
  MAX_STRUCTURED_ANSWER_PARTS,
  MIN_PART_TEXT_CODE_POINTS,
  MIN_STRUCTURED_ANSWER_PARTS,
  measureStructuredAnswerBytes,
  parseStructuredAnswer,
  RESERVED_ANSWER_NAMESPACE,
  STRUCTURED_ANSWER_REGISTRY,
  STRUCTURED_ANSWER_VERSION,
  StructuredAnswerPartSchema,
  StructuredAnswerSchema,
} from "./structured_answer.js";
export type {
  ActualOutcome,
  LatestToolErrorCode,
  LatestToolErrorSchemaVersion,
  LatestToolResult,
  M0ToolErrorCode,
  M0ToolResult,
  M1ToolErrorCode,
  M1ToolErrorCodeNew,
  M1ToolErrorSchemaVersion,
  M1ToolResult,
  ReportedOutcome,
  ResultDisposition,
  RunErrorCode,
  RunErrorSchemaVersion,
  ToolCategory,
  ToolDescriptor,
  ToolErrorCode,
  ToolErrorSchemaVersion,
  ToolName,
  ToolResult,
} from "./tools.js";
export {
  ActualOutcomeSchema,
  KNOWN_LATEST_TOOL_ERROR_CODES,
  KNOWN_M0_TOOL_ERROR_CODES,
  LATEST_TOOL_ERROR_CODE_REGISTRY,
  LATEST_TOOL_ERROR_CODES,
  LatestToolErrorCodeSchema,
  LatestToolResultSchema,
  M0_RUN_ERROR_CODES,
  M0_TOOL_ERROR_CODES,
  M0ToolErrorCodeSchema,
  M0ToolResultSchema,
  M1_TOOL_ERROR_CODE_REGISTRY,
  M1_TOOL_ERROR_CODES,
  M1ToolErrorCodeNewSchema,
  M1ToolErrorCodeSchema,
  M1ToolResultSchema,
  parseLatestToolErrorCode,
  parseM0ToolErrorCode,
  parseM1ToolErrorCode,
  parseRunErrorCode,
  parseToolErrorCode,
  ReportedOutcomeSchema,
  ResultDispositionSchema,
  RUN_ERROR_CODE_REGISTRY,
  RunErrorCodeSchema,
  TOOL_BUDGET_DEFAULTS,
  TOOL_ERROR_CODE_REGISTRY,
  ToolCategorySchema,
  ToolDescriptorSchema,
  ToolErrorCodeSchema,
  ToolNameSchema,
  ToolResultSchema,
} from "./tools.js";
export type {
  TurnInputSchemaVersion,
  TurnInputV1,
  UserTextTurnInputV1,
} from "./turn_input.js";
export {
  MAX_USER_TEXT_LENGTH,
  parseTurnInput,
  TURN_INPUT_REGISTRY,
  TurnInputV1Schema,
  UserTextTurnInputV1Schema,
} from "./turn_input.js";
